spring:
  cloud:
    nacos: #
      discovery:
        server-addr: http://localhost:8848
      config:
        server-addr: http://localhost:8848
        file-extension: yaml
  redis: #
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
